### ISSUE TITLE
add backboneconf

### ISSUE THREAD

**Issue by A** [FrontenderMagazine/conference-videos#23]
Чтобы не забыть:
http://backboneconf.com/2013/

**Comment by denji** [comment]
- https://github.com/RichardLitt/awesome-conferences
- ~~https://gist.github.com/maxogden/322a649ff84fe1c2a680~~
- ~~https://gist.github.com/dxnn/55ebf7363cc5bcc7677b~~
- http://gdg.org.ua/ ( https://github.com/GDG-Ukraine/ )
